;;; gif-screencast-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gif-screencast.el

(autoload 'gif-screencast "gif-screencast" "\
Start recording the GIF.
A screenshot is taken before every command runs." t)
(register-definition-prefixes "gif-screencast" '("gif-screencast-"))

;;; End of scraped data

(provide 'gif-screencast-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gif-screencast-autoloads.el ends here
